### ISSUE TITLE
Cannot run command runbridged,is there something wrong?

### ISSUE THREAD

**Issue by RichieJi** [DMOJ/site#1015]
(dmojsite) root@iZ28wtpdbtlZ:/alidata/site# python manage.py runbridged
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/alidata/dmojsite/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/alidata/dmojsite/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/alidata/dmojsite/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/alidata/dmojsite/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/alidata/site/judge/management/commands/runbridged.py", line 23, in handle
    judge_server = JudgeServer(settings.BRIDGED_JUDGE_ADDRESS, judge_handler)
  File "/alidata/site/judge/bridge/judgeserver.py", line 19, in __init__
    super(JudgeServer, self).__init__(*args, **kwargs)
  File "/alidata/site/event_socket_server/engines/poll_server.py", line 24, in __init__
    super(PollServer, self).__init__(*args, **kwargs)
  File "/alidata/site/event_socket_server/base_server.py", line 49, in __init__
    sock.bind(sa)
OSError: [Errno 99] Cannot assign requested address

**Comment by kiritofeng** [comment]
This is almost certainly a user-side configuration issue and not an actual bug.
