### ISSUE TITLE
Getting ImportError: cannot import name Celery

### ISSUE THREAD

**Issue by diwakarvats** [DMOJ/site#1043]
Hi
when run command python manage.py check i am getting following error 
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/debdmoj/judge/site/dmoj/__init__.py", line 1, in <module>
    from dmoj.celery import app as celery_app
  File "/home/debdmoj/judge/site/dmoj/celery.py", line 5, in <module>
    from celery import Celery
ImportError: cannot import name Celery

**Comment by kiritofeng** [comment]
I see that you are still using Python 2; the site is now on Python 3, and not backwards compatible.

Can you see if the error persists after switching to Python 3?

**Comment by Xyene** [comment]
Closing issue due to inactivity; feel free to reopen if issue persists.
