### ISSUE TITLE
Unexpected argument while running python manage.py check

### ISSUE THREAD

**Issue by somanshreddy** [DMOJ/site#1058]
After running the command
`python manage.py check`

The error that I got was 

`TypeError: __init__() got an unexpected keyword argument 'css'`

If I comment the above line then I get the following error 

`TypeError: __init__() got an unexpected keyword argument 'template'`

Given below is the full stack trace

```pytb
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/somansh/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/somansh/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/somansh/.local/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/somansh/.local/lib/python3.5/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/home/somansh/.local/lib/python3.5/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/somansh/.local/lib/python3.5/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/somansh/.local/lib/python3.5/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/somansh/site/judge/admin/__init__.py", line 4, in <module>
    from judge.admin.comments import CommentAdmin
  File "/home/somansh/site/judge/admin/comments.py", line 11, in <module>
    class CommentForm(ModelForm):
  File "/home/somansh/site/judge/admin/comments.py", line 12, in CommentForm
    class Meta:
  File "/home/somansh/site/judge/admin/comments.py", line 18, in Meta
    widgets['body'] = HeavyPreviewAdminPageDownWidget(preview=reverse_lazy('comment_preview'))
  File "/home/somansh/site/judge/widgets/pagedown.py", line 64, in __init__
    super(HeavyPreviewPageDownWidget, self).__init__(*args, **kwargs)
  File "/home/somansh/site/judge/widgets/pagedown.py", line 33, in __init__
    super(PagedownWidget, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'template'
```

**Comment by Xyene** [comment]
The latest version of `django-pagedown` is not compatible with the current version of the site. We'll get around to fixing it, but in the meantime you can try installing an older version of it.
