### ISSUE TITLE
Eventual PyPy/uwsgi memory leak

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#171]
After leaving the server on for days, the system will eventually run out of memory.

```pytb
Traceback (most recent call last):
  File "/code/pypy-virtenv/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/pypy-virtenv/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/code/pypy-virtenv/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "./judge/views/problem.py", line 150, in get
    maker.make()
  File "./judge/pdf_problems.py", line 233, in make
    self.proc = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, cwd=self.dir)
  File "/opt/pypy2/lib-python/2.7/subprocess.py", line 725, in __init__
    errread, errwrite)
  File "/opt/pypy2/lib-python/2.7/subprocess.py", line 1242, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Comment by quantum5** [comment]
Potential solution: `uwsgi`'s `max-worker-lifetime` option, set to like `32400`.

**Comment by quantum5** [comment]
On the other hand, we can try `max-requests` which might be better, or can be used in conjunction with the `max-worker-lifetime`. Should probably set `max-requests-delta` to avoid all workers restarting together.

**Comment by quantum5** [comment]
Will also tune the GC flag a bit. Stats showed this is caused by massive load spike.

**Comment by quantum5** [comment]
Does not seem to happen again.
