### ISSUE TITLE
Handle MySQL server has gone away

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#185]
``` pytb
Error in packet handling (Judge-side)
Traceback (most recent call last):
  File "/code/site/judge/bridge/judgehandler.py", line 168, in packet
    handler(data)
  File "/code/site/judge/bridge/judgecallback.py", line 262, in on_test_case
    submission = Submission.objects.get(id=packet['submission-id'])
  File "/code/pypy-virtenv/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/code/pypy-virtenv/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/code/pypy-virtenv/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/code/pypy-virtenv/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/code/pypy-virtenv/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/code/pypy-virtenv/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/code/pypy-virtenv/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/code/pypy-virtenv/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/code/pypy-virtenv/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/code/pypy-virtenv/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/code/pypy-virtenv/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "/code/pypy-virtenv/site-packages/MySQLdb/cursors.py", line 220, in execute
    self.errorhandler(self, exc, value)
  File "/code/pypy-virtenv/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
```

We should like catch this on ping and reconnect. MySQL doesn't go AWOL but sometimes have to be restarted.

**Comment by quantum5** [comment]
Might be better to fix it after #183

**Comment by quantum5** [comment]
Catching this is really PITA. May be we should copy python's `_eintr_retry_call(func, *args, **kwargs)`.

**Comment by quantum5** [comment]
I think we have put in some fix for this a long time ago.
