### ISSUE TITLE
HTML parser combination

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#274]
Since we will end up with three `lxml` parsers from #270, #259, and #273, I suggest we make an object that can be converted to a safe string, but stores the `lxml` `ElementTree`, so we don't keep parsing it again and again. If a filter takes in a string, then it should make this new object, and output it.

**Comment by Xyene** [comment]
`lxml` parser dies on contest pages if the description is empty.

```python
Internal Server Error: /contest/vmss7w15c6
Traceback (most recent call last):
  File "/code/pypy-virtenv/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/code/pypy-virtenv/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/code/pypy-virtenv/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/code/pypy-virtenv/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/code/pypy-virtenv/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/code/pypy-virtenv/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/code/pypy-virtenv/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/code/pypy-virtenv/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/code/pypy-virtenv/site-packages/django/templatetags/cache.py", line 48, in render
    value = self.nodelist.render(context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 957, in render
    output = self.filter_expression.resolve(context)
  File "/code/pypy-virtenv/site-packages/django/template/base.py", line 674, in resolve
    new_obj = func(obj, *arg_vals)
  File "./judge/templatetags/camo_proxy.py", line 56, in proxy_images
    return client.parse_html(text)
  File "./judge/templatetags/camo_proxy.py", line 36, in parse_html
    doc = lxml_tree.fromstring(string)
  File "./judge/lxml_tree.py", line 43, in fromstring
    return HTMLTreeString(str)
  File "./judge/lxml_tree.py", line 7, in __init__
    self._tree = html.fromstring(str)
  File "/code/pypy-virtenv/site-packages/lxml/html/__init__.py", line 726, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/code/pypy-virtenv/site-packages/lxml/html/__init__.py", line 614, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3103, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70569)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106403)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105194)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99876)
XMLSyntaxError: line 57: Unexpected end tag : p
```

**Comment by quantum5** [comment]
The basic `HTMLTreeString` is working solidly for a long time.
