### ISSUE TITLE
Comparing revisions with `django-reversion-compare`

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#32]
Implementation is simply subclassing a different class in `admin.py`, but it requires Django 1.7 (#30). The base feature is already implemented in #29.

**Comment by quantum5** [comment]
```pytb
Internal Server Error: /admin/judge/contest/49/history/compare/
Traceback (most recent call last):
  File "/code/dmoj-virtenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/dmoj-virtenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/code/dmoj-virtenv/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/code/dmoj-virtenv/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 206, in inner
    return view(request, *args, **kwargs)
  File "/code/dmoj-virtenv/local/lib/python2.7/site-packages/reversion_compare/admin.py", line 692, in compare_view
    compare_data, has_unfollowed_fields = self.compare(obj, version1, version2)
  File "/code/dmoj-virtenv/local/lib/python2.7/site-packages/reversion_compare/admin.py", line 646, in compare
    if not obj_compare.changed():
  File "/code/dmoj-virtenv/local/lib/python2.7/site-packages/reversion_compare/admin.py", line 246, in changed
    info = self.get_m2m_change_info()
  File "/code/dmoj-virtenv/local/lib/python2.7/site-packages/reversion_compare/admin.py", line 298, in get_m2m_change_info
    m2m_data1, m2m_data2 = self.get_many_to_many()
  File "/code/dmoj-virtenv/local/lib/python2.7/site-packages/reversion_compare/admin.py", line 276, in get_many_to_many
    m2m_data1, m2m_data2 = self._get_both_results("get_many_to_many")
  File "/code/dmoj-virtenv/local/lib/python2.7/site-packages/reversion_compare/admin.py", line 264, in _get_both_results
    result1 = self._get_result(self.compare_obj1, func_name)
  File "/code/dmoj-virtenv/local/lib/python2.7/site-packages/reversion_compare/admin.py", line 260, in _get_result
    result = func()
  File "/code/dmoj-virtenv/local/lib/python2.7/site-packages/reversion_compare/admin.py", line 126, in get_many_to_many
    ids = [int(v) for v in self.value] # is: version.field_dict[field.name]
ValueError: invalid literal for int() with base 10: 'F'
```

Somehow doesn't work for `Contest`s.

**Comment by Xyene** [comment]
Probably caused by <https://github.com/jedie/django-reversion-compare/issues/44>.

**Comment by vdboor** [comment]
One part of the solution might be using a placeholder object instead of 

```self.value = version.field_dict.get(field_name, _("Field Didn't exist!"))```

which gets parsed in a loop at:

```ids = [int(v) for v in self.value]```
