### ISSUE TITLE
NonExistentTimeError in calender view

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#330]
```python
Internal Server Error: /contests/1948/5/
Traceback (most recent call last):
  File "/code/pypy-virtenv/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/pypy-virtenv/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/code/pypy-virtenv/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "./judge/views/contests.py", line 211, in get
    return self.render()
  File "./judge/views/contests.py", line 214, in render
    context = self.get_context_data()
  File "./judge/views/contests.py", line 250, in get_context_data
    context['calendar'] = self.get_table()
  File "./judge/views/contests.py", line 235, in get_table
    starts, ends, oneday = self.get_contest_data(timezone.make_aware(datetime.combine(calendar[0][0], time.min)),
  File "/code/pypy-virtenv/site-packages/django/utils/timezone.py", line 358, in make_aware
    return timezone.localize(value, is_dst=None)
  File "/code/pypy-virtenv/site-packages/pytz/tzinfo.py", line 327, in localize
    raise NonExistentTimeError(dt)
NonExistentTimeError: 1948-04-25 00:00:00
```

**Comment by quantum5** [comment]
How can 1948 not exist? Even unix time goes before that.
