### ISSUE TITLE
OverflowError in calender view

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#332]
<https://dmoj.ca/contests/1/1/>

```python
Traceback (most recent call last):
  File "/code/pypy-virtenv/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/pypy-virtenv/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/code/pypy-virtenv/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "./judge/views/contests.py", line 211, in get
    return self.render()
  File "./judge/views/contests.py", line 214, in render
    context = self.get_context_data()
  File "./judge/views/contests.py", line 250, in get_context_data
    context['calendar'] = self.get_table()
  File "./judge/views/contests.py", line 233, in get_table
    calendar = Calendar(self.firstweekday).monthdatescalendar(self.year, self.month)
  File "/opt/pypy-2.6/lib-python/2.7/calendar.py", line 199, in monthdatescalendar
    dates = list(self.itermonthdates(year, month))
  File "/opt/pypy-2.6/lib-python/2.7/calendar.py", line 160, in itermonthdates
    date -= datetime.timedelta(days=days)
  File "/opt/pypy-2.6/lib_pypy/datetime.py", line 970, in __sub__
    return self + timedelta(-other.days)
  File "/opt/pypy-2.6/lib_pypy/datetime.py", line 960, in __add__
    self._checkOverflow(t.year)
  File "/opt/pypy-2.6/lib_pypy/datetime.py", line 952, in _checkOverflow
    (year, MINYEAR, MAXYEAR))
OverflowError: date +/-: result year 0 not in 1..9999
```

Similar to #330, except this should never occur during search engine crawling. It can, however, be caused by an overly curious user.

**Comment by Xyene** [comment]
A similar error caused by passing year 9999: <https://dmoj.ca/contests/9999/12/>

```python
Traceback (most recent call last):
  File "/code/pypy-virtenv/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/pypy-virtenv/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/code/pypy-virtenv/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "./judge/views/contests.py", line 211, in get
    return self.render()
  File "./judge/views/contests.py", line 214, in render
    context = self.get_context_data()
  File "./judge/views/contests.py", line 250, in get_context_data
    context['calendar'] = self.get_table()
  File "./judge/views/contests.py", line 236, in get_table
    timezone.make_aware(datetime.combine(calendar[-1][-1], time.min)))
  File "/code/pypy-virtenv/site-packages/django/utils/timezone.py", line 358, in make_aware
    return timezone.localize(value, is_dst=None)
  File "/code/pypy-virtenv/site-packages/pytz/tzinfo.py", line 309, in localize
    loc_dt = dt + delta
  File "/opt/pypy-2.6/lib_pypy/datetime.py", line 1869, in __add__
    self._checkOverflow(t.year)
  File "/opt/pypy-2.6/lib_pypy/datetime.py", line 952, in _checkOverflow
    (year, MINYEAR, MAXYEAR))
OverflowError: date +/-: result year 10000 not in 1..9999
```
