### ISSUE TITLE
django-reversion-compare broken

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#358]
```python
Traceback (most recent call last):
  File "/code/pypy-virtenv/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/code/pypy-virtenv/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/pypy-virtenv/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/code/pypy-virtenv/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/code/pypy-virtenv/site-packages/django/contrib/admin/sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "/code/pypy-virtenv/site-packages/reversion_compare/admin.py", line 175, in compare_view
    compare_data, has_unfollowed_fields = self.compare(obj, version1, version2)
  File "/code/pypy-virtenv/site-packages/reversion_compare/mixins.py", line 132, in compare
    if not obj_compare.changed():
  File "/code/pypy-virtenv/site-packages/reversion_compare/compare.py", line 250, in changed
    info = self.get_m2o_change_info()
  File "/code/pypy-virtenv/site-packages/reversion_compare/compare.py", line 293, in get_m2o_change_info
    m2o_data1, m2o_data2 = self.get_reverse_foreign_key()
  File "/code/pypy-virtenv/site-packages/reversion_compare/compare.py", line 285, in get_reverse_foreign_key
    return self._get_both_results("get_reverse_foreign_key")
  File "/code/pypy-virtenv/site-packages/reversion_compare/compare.py", line 269, in _get_both_results
    result1 = self._get_result(self.compare_obj1, func_name)
  File "/code/pypy-virtenv/site-packages/reversion_compare/compare.py", line 265, in _get_result
    result = func()
  File "/code/pypy-virtenv/site-packages/reversion_compare/compare.py", line 106, in get_reverse_foreign_key
    return self.get_many_to_something(ids, related_model, is_reverse=True)
  File "/code/pypy-virtenv/site-packages/reversion_compare/compare.py", line 165, in get_many_to_something
    deleted = [d for d in reversion.get_deleted(related_model) if d.revision == old_revision]
AttributeError: 'module' object has no attribute 'get_deleted'
```

**Comment by quantum5** [comment]
I forked `django-reversion-compare` and fixed this exception in jedie/django-reversion-compare#51.
