### ISSUE TITLE
Event Socket Server Race

### ISSUE THREAD

**Issue by quantum5** [DMOJ/site#5]
Closes file handles on error conditions despite being in use.

```pytb
Traceback (most recent call last):

  File "/code/site/judge/bridge/judgelist.py", line 23, in _handle_free_judge
    judge.submit(id, problem, language, source)

  File "/code/site/judge/bridge/judgehandler.py", line 124, in submit
    'short-circuit': short,

  File "/code/site/event_socket_server/helpers.py", line 35, in send
    self._send(size_pack.pack(len(data)) + data, callback)

  File "/code/site/event_socket_server/handler.py", line 17, in _send
    return self.server.send(self, data, callback)

  File "/code/site/event_socket_server/base_server.py", line 146, in send
    self._send_queue[client.fileno()].append(SendMessage(data, callback))

  File "/code/site/event_socket_server/handler.py", line 11, in fileno
    return self._socket.fileno()

  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)

  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')

error: [Errno 9] Bad file descriptor
```

**Comment by quantum5** [comment]
The only way we will fix this is through #183
