### ISSUE TITLE
Installing the site results in weird database error

### ISSUE THREAD

**Issue by mraron** [DMOJ/site#647]
According to docs I'm at the point when I should run python manage.py check. But it gives the error:

`django.db.utils.ProgrammingError: (1146, "Table 'dmoj.judge_language' doesn't exist")`

I followed the steps exactly and it looked suspicious, because until that point only the database user had been created. Then I tried checking out different commits and it didn't gave error in some. I narrowed down the problem between commits 9b88fb946e9c0c49d10fa0ff24b2048da6400b9d and 846fbed63990736b25dd7c5b1522f2060cacbb53

**Comment by Xyene** [comment]
Did you run `python manage.py migrate` beforehand? These types of errors occur if the database schema hasn't been set up yet.

**Comment by Xyene** [comment]
Specifically: yes, this is probably an issue in that having a schema set up became required between those commits you've listed, but migrating the db beforehand should solve the immediate problem.

**Comment by mraron** [comment]
The problem is, even if I run `python manage.py migrate` I get the exact same error. It seems like a problem in manage.py, no matter how do I call it: I get the error.

**Comment by quantum5** [comment]
Please send the full traceback.

**Comment by mraron** [comment]
Here's the full traceback of migrate command:

`/home/dante/dmojsite/src/dmoj-wpadmin/wpadmin/__init__.py:20:` UserWarning: Django WP Admin 1.10.2 is not compatible with Django 1.11.8 and may not work properly. You should install Django WP Admin from 1.11.x branch.
  UserWarning)
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/home/dante/site/judge/apps.py", line 31, in ready
    lang = Language.get_python2()
  File "/home/dante/site/judge/models/runtime.py", line 89, in get_python2
    return Language.objects.get_or_create(key='PY2', name='Python 2')[0]
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
django.db.utils.ProgrammingError: (1146, "Table 'dmoj.judge_language' doesn't exist")`

**Comment by quantum5** [comment]
Fixed in latest commit.

**Comment by mraron** [comment]
Thanks. That was fast :D
