### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by mraron** [DMOJ/site#648]
Following the docs, when trying to run `python manage.py check` I get 

```
/home/dante/dmojsite/src/dmoj-wpadmin/wpadmin/__init__.py:20: UserWarning: Django WP Admin 1.10.2 is not compatible with Django 1.11.8 and may not work properly. You should install Django WP Admin from 1.11.x branch.
  UserWarning)
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/apps/config.py", line 120, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named pyjade.ext
```
In my previous issue I worked it around and placed dmoj's pyjade in requirements.txt. It worked but it's definitely not optimal. Also after I put pyjade into the file I got gravatar module missing, I also successfully found the adequate gravatar module from pip and installed it and it worked.

**Comment by quantum5** [comment]
Both issues have been fixed. Please uninstall pyjade and gravatar stuff.

**Comment by mraron** [comment]
Thank you, done.

**Comment by mraron** [comment]
But I get this error:

```
/home/dante/dmojsite/src/dmoj-wpadmin/wpadmin/__init__.py:20: UserWarning: Django WP Admin 1.10.2 is not compatible with Django 1.11.8 and may not work properly. You should install Django WP Admin from 1.11.x branch.
  UserWarning)
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/core/management/commands/check.py", line 68, in handle
    fail_level=getattr(checks, options['fail_level']),
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/dante/dmojsite/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/dante/site/dmoj/urls.py", line 20, in <module>
    from judge.views.select2 import UserSelect2View, OrganizationSelect2View, ProblemSelect2View, CommentSelect2View, \
  File "/home/dante/site/judge/views/select2.py", line 8, in <module>
    from judge.jinja2.gravatar import get_gravatar_url
ImportError: cannot import name get_gravatar_url

```

**Comment by quantum5** [comment]
Try pulling again.

**Comment by mraron** [comment]
It's ok now, as far as I see.
