### ISSUE TITLE
socket.error: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by KaiserW** [DMOJ/site#702]
I'm trying to install DMOJ on a cloud machine, all is going well until `python manage.py runbridged`, following error was produced:

`
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/root/dmojsite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/root/dmojsite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/dmojsite/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/dmojsite/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/root/site/judge/management/commands/runbridged.py", line 23, in handle
    judge_server = JudgeServer(settings.BRIDGED_JUDGE_ADDRESS, judge_handler)
  File "/root/site/judge/bridge/judgeserver.py", line 19, in __init__
    super(JudgeServer, self).__init__(*args, **kwargs)
  File "/root/site/event_socket_server/engines/poll_server.py", line 24, in __init__
    super(PollServer, self).__init__(*args, **kwargs)
  File "/root/site/event_socket_server/base_server.py", line 40, in __init__
    sock.bind(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
`

Thank you in advance for any help.

**Comment by Xyene** [comment]
You should play around with `local_settings.py`'s `BRIDGED_JUDGE_ADDRESS` declaration and set it to a host/port combo that is unused.
