### ISSUE TITLE
NameError: global name 'ContestSubmission' is not defined

### ISSUE THREAD

**Issue by knovoselic** [DMOJ/site#923]
Hi!

I'm getting the following error when I try to rejudge a problem:

```
SIGSEGV: invalid_state
corrupt page /admin/judge/contest/3/judge/10/
site: fatal signal: Segmentation fault
site died (signal 500, exit -11)

panic: go back
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/site/judge/admin/contest.py", line 171, in rejudge_view
    queryset = ContestSubmission.objects.filter(problem_id=problem_id).select_related('submission')
NameError: global name 'ContestSubmission' is not defined
```

This only happens when I try to rejudge submissions from inside a contest edit page. When I do it from Submissions page, rejudging works fine.

Is this a known issue? Any idea what the problem could be? Thanks!

**Comment by quantum5** [comment]
This has been fixed in 9052e79bc7478d04bed645262e86f796c0e62128. Please pull the latest version.
