### ISSUE TITLE
SyntaxError in manage.py

### ISSUE THREAD

**Issue by Finchiedev** [DMOJ/site#934]
Hello,
For context, I am using Arch Linux (in case that helps)
While following the docs on installing the site, I came across this error when running `manage.py` inside of the virtualenv as instructed:
`
(dmojsite) [finchie@arch site]$ python manage.py collectstatic

Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/finchie/DMOJ/dmojsite/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/finchie/DMOJ/dmojsite/lib/python3.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/finchie/DMOJ/dmojsite/lib/python3.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/finchie/DMOJ/dmojsite/lib/python3.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/finchie/DMOJ/dmojsite/lib/python3.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/finchie/DMOJ/dmojsite/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/finchie/DMOJ/site/dmoj/settings.py", line 391
    exec f in globals()
         ^
SyntaxError: invalid syntax
`

Apologies if this is a silly error, but I would be very grateful if someone could point me in the right direction!

**Comment by kiritofeng** [comment]
Site has not yet been ported to Python 3, please use Python 2.

**Comment by Finchiedev** [comment]
Thanks for the heads up!
